# function for getting the best corelations from the dataset

# function to generate train model using some weights

# predict the score generated by the each algorithm used and showcase the generated dataset

# compare the result and make a conclusion

# additionally, we can make a graph visualization of every algorithm and see differeces
